# EDA — Intermediate Datasets
Loads all 5 intermediate parquets with Polars and runs basic profiling on each.

In [17]:
import sys
from pathlib import Path

# Make project root importable regardless of where the notebook is opened from
PROJECT_ROOT = Path("__file__").resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import polars as pl
from src.common.utils.config import load_config

conf = load_config()
INTERMEDIATE = "../" + conf["data"]["intermediate_path"]
print("Intermediate path:", INTERMEDIATE)

Intermediate path: ../data/Intermediate/

In [18]:
%ls ../data

Intermediate/ input/        output/

## 1. base_sales_enriched

In [19]:
base_sales = pl.read_parquet(f"{INTERMEDIATE}/base_sales_enriched.parquet")
print("Shape:", base_sales.shape)
base_sales.dtypes  # column types

Shape: (6799893, 18)

[Datetime(time_unit='us', time_zone=None),
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 Float64,
 Int64,
 Float64,
 String,
 String,
 String,
 String,
 String,
 String,
 String]

In [20]:
base_sales.describe()

shape: (9, 19)
┌────────────┬────────────┬───────────┬───────────┬───┬─────────┬──────────┬───────────┬───────────┐
│ statistic  ┆ document_d ┆ documnet_ ┆ outlet_id ┆ … ┆ brand   ┆ region   ┆ district  ┆ province  │
│ ---        ┆ ate        ┆ number    ┆ ---       ┆   ┆ ---     ┆ ---      ┆ ---       ┆ ---       │
│ str        ┆ ---        ┆ ---       ┆ str       ┆   ┆ str     ┆ str      ┆ str       ┆ str       │
│            ┆ str        ┆ str       ┆           ┆   ┆         ┆          ┆           ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪══════════╪═══════════╪═══════════╡
│ count      ┆ 6799893    ┆ 6799893   ┆ 6799893   ┆ … ┆ 6799893 ┆ 6799893  ┆ 6799893   ┆ 6799893   │
│ null_count ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 0       ┆ 0        ┆ 0         ┆ 0         │
│ mean       ┆ 2017-09-14 ┆ null      ┆ null      ┆ … ┆ null    ┆ null     ┆ null      ┆ null      │
│            ┆ 10:58:40.0 ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│            ┆ 70801      ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ std        ┆ null       ┆ null      ┆ null      ┆ … ┆ null    ┆ null     ┆ null      ┆ null      │
│ min        ┆ 2015-01-01 ┆ 001800485 ┆ 0         ┆ … ┆ brand_1 ┆ region_1 ┆ district_ ┆ province_ │
│            ┆ 00:00:00   ┆ 5         ┆           ┆   ┆         ┆          ┆ 1         ┆ 1         │
│ 25%        ┆ 2016-06-09 ┆ null      ┆ null      ┆ … ┆ null    ┆ null     ┆ null      ┆ null      │
│            ┆ 00:00:00   ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 50%        ┆ 2017-10-04 ┆ null      ┆ null      ┆ … ┆ null    ┆ null     ┆ null      ┆ null      │
│            ┆ 00:00:00   ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 75%        ┆ 2018-12-19 ┆ null      ┆ null      ┆ … ┆ null    ┆ null     ┆ null      ┆ null      │
│            ┆ 00:00:00   ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ max        ┆ 2020-03-19 ┆ inv044100 ┆ s097255   ┆ … ┆ brand_6 ┆ region_9 ┆ district_ ┆ province_ │
│            ┆ 00:00:00   ┆ 079       ┆           ┆   ┆         ┆          ┆ 9         ┆ 9         │
└────────────┴────────────┴───────────┴───────────┴───┴─────────┴──────────┴───────────┴───────────┘

In [21]:
base_sales.head()

shape: (5, 18)
┌────────────┬────────────┬───────────┬───────────┬───┬─────────┬──────────┬───────────┬───────────┐
│ document_d ┆ documnet_n ┆ outlet_id ┆ territory ┆ … ┆ brand   ┆ region   ┆ district  ┆ province  │
│ ate        ┆ umber      ┆ ---       ┆ _id       ┆   ┆ ---     ┆ ---      ┆ ---       ┆ ---       │
│ ---        ┆ ---        ┆ str       ┆ ---       ┆   ┆ str     ┆ str      ┆ str       ┆ str       │
│ datetime[μ ┆ str        ┆           ┆ str       ┆   ┆         ┆          ┆           ┆           │
│ s]         ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪══════════╪═══════════╪═══════════╡
│ 2015-01-01 ┆ inv0171090 ┆ 709293    ┆ 171       ┆ … ┆ brand_1 ┆ region_1 ┆ district_ ┆ province_ │
│ 00:00:00   ┆ 10         ┆           ┆           ┆   ┆         ┆          ┆ 1         ┆ 1         │
│ 2015-01-01 ┆ inv0171090 ┆ 709293    ┆ 171       ┆ … ┆ brand_4 ┆ region_1 ┆ district_ ┆ province_ │
│ 00:00:00   ┆ 10         ┆           ┆           ┆   ┆         ┆          ┆ 1         ┆ 1         │
│ 2015-01-01 ┆ inv0171090 ┆ 709293    ┆ 171       ┆ … ┆ brand_1 ┆ region_1 ┆ district_ ┆ province_ │
│ 00:00:00   ┆ 10         ┆           ┆           ┆   ┆         ┆          ┆ 1         ┆ 1         │
│ 2015-01-01 ┆ inv0241116 ┆ 016780    ┆ 241       ┆ … ┆ brand_2 ┆ region_3 ┆ district_ ┆ province_ │
│ 00:00:00   ┆ 13         ┆           ┆           ┆   ┆         ┆          ┆ 3         ┆ 3         │
│ 2015-01-01 ┆ inv0158100 ┆ 717003    ┆ 158       ┆ … ┆ brand_2 ┆ region_4 ┆ district_ ┆ province_ │
│ 00:00:00   ┆ 27         ┆           ┆           ┆   ┆         ┆          ┆ 4         ┆ 4         │
└────────────┴────────────┴───────────┴───────────┴───┴─────────┴──────────┴───────────┴───────────┘

## 2. outlet_sku_monthly_demand

In [22]:
outlet_sku = pl.read_parquet(INTERMEDIATE + "/outlet_sku_monthly_demand.parquet")
print("Shape:", outlet_sku.shape)
outlet_sku.dtypes

Shape: (123104457, 18)

[String,
 String,
 String,
 Int64,
 Float64,
 Int64,
 Float64,
 Int64,
 Float64,
 UInt32,
 UInt32,
 String,
 String,
 String,
 String,
 String,
 String,
 String]

In [23]:
outlet_sku.describe()

shape: (9, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ outlet_id ┆ item_code ┆ year_mont ┆ … ┆ province  ┆ product_c ┆ product_l ┆ brand    │
│ ---       ┆ ---       ┆ ---       ┆ h         ┆   ┆ ---       ┆ ategory   ┆ ine       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 123104457 ┆ 123104457 ┆ 123104457 ┆ … ┆ 123104457 ┆ 123104457 ┆ 123104457 ┆ 12310445 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ min       ┆ 0         ┆ gf1000203 ┆ 2015-01   ┆ … ┆ province_ ┆ cat_1     ┆ prod_line ┆ brand_1  │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆           ┆ 1         ┆          │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max       ┆ s097255   ┆ wf9000902 ┆ 2020-03   ┆ … ┆ province_ ┆ cat_7     ┆ prod_line ┆ brand_6  │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆ 9         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
outlet_sku.head()

shape: (5, 18)
┌───────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ outlet_id ┆ item_code ┆ year_month ┆ net_quant ┆ … ┆ province  ┆ product_c ┆ product_l ┆ brand   │
│ ---       ┆ ---       ┆ ---        ┆ ity       ┆   ┆ ---       ┆ ategory   ┆ ine       ┆ ---     │
│ str       ┆ str       ┆ str        ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str     │
│           ┆           ┆            ┆ i64       ┆   ┆           ┆ str       ┆ str       ┆         │
╞═══════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ 87771     ┆ pf0033301 ┆ 2015-01    ┆ 0         ┆ … ┆ province_ ┆ cat_2     ┆ prod_line ┆ brand_1 │
│           ┆           ┆            ┆           ┆   ┆ 3         ┆           ┆ 3         ┆         │
│ 87771     ┆ pf0033301 ┆ 2015-02    ┆ 0         ┆ … ┆ province_ ┆ cat_2     ┆ prod_line ┆ brand_1 │
│           ┆           ┆            ┆           ┆   ┆ 3         ┆           ┆ 3         ┆         │
│ 87771     ┆ pf0033301 ┆ 2015-03    ┆ 0         ┆ … ┆ province_ ┆ cat_2     ┆ prod_line ┆ brand_1 │
│           ┆           ┆            ┆           ┆   ┆ 3         ┆           ┆ 3         ┆         │
│ 87771     ┆ pf0033301 ┆ 2015-04    ┆ 0         ┆ … ┆ province_ ┆ cat_2     ┆ prod_line ┆ brand_1 │
│           ┆           ┆            ┆           ┆   ┆ 3         ┆           ┆ 3         ┆         │
│ 87771     ┆ pf0033301 ┆ 2015-05    ┆ 0         ┆ … ┆ province_ ┆ cat_2     ┆ prod_line ┆ brand_1 │
│           ┆           ┆            ┆           ┆   ┆ 3         ┆           ┆ 3         ┆         │
└───────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

## 3. outlet_monthly_activity

In [25]:
outlet_activity = pl.read_parquet(INTERMEDIATE + "/outlet_monthly_activity.parquet")
print("Shape:", outlet_activity.shape)
outlet_activity.dtypes

Shape: (7319529, 15)

[String,
 String,
 UInt32,
 Int64,
 Float64,
 UInt32,
 Int64,
 Float64,
 UInt32,
 UInt32,
 String,
 String,
 String,
 String,
 String]

In [26]:
outlet_activity.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ statistic ┆ outlet_id ┆ year_mont ┆ n_invoice ┆ … ┆ territory ┆ region   ┆ district  ┆ province  │
│ ---       ┆ ---       ┆ h         ┆ s         ┆   ┆ _id       ┆ ---      ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str      ┆ str       ┆ str       │
│           ┆           ┆ str       ┆ f64       ┆   ┆ str       ┆          ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ count     ┆ 7319529   ┆ 7319529   ┆ 7.319529e ┆ … ┆ 7319529   ┆ 7319529  ┆ 7319529   ┆ 7319529   │
│           ┆           ┆           ┆ 6         ┆   ┆           ┆          ┆           ┆           │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0       ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 0         │
│ t         ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ mean      ┆ null      ┆ null      ┆ 0.890542  ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ std       ┆ null      ┆ null      ┆ 2.261257  ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ min       ┆ 0         ┆ 2015-01   ┆ 0.0       ┆ … ┆ 10        ┆ region_1 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 1         ┆ 1         │
│ 25%       ┆ null      ┆ null      ┆ 0.0       ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null      ┆ 0.0       ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null      ┆ 1.0       ┆ … ┆ null      ┆ null     ┆ null      ┆ null      │
│ max       ┆ s097255   ┆ 2020-03   ┆ 223.0     ┆ … ┆ 99        ┆ region_9 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 9         ┆ 9         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [27]:
outlet_activity.head()

shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ outlet_id ┆ year_mont ┆ n_invoice ┆ gross_qua ┆ … ┆ territory ┆ region   ┆ district  ┆ province  │
│ ---       ┆ h         ┆ s         ┆ ntity     ┆   ┆ _id       ┆ ---      ┆ ---       ┆ ---       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str      ┆ str       ┆ str       │
│           ┆ str       ┆ u32       ┆ i64       ┆   ┆ str       ┆          ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 41530     ┆ 2015-01   ┆ 0         ┆ 0         ┆ … ┆ 2         ┆ region_5 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 22        ┆ 9         │
│ 41530     ┆ 2015-02   ┆ 0         ┆ 0         ┆ … ┆ 2         ┆ region_5 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 22        ┆ 9         │
│ 41530     ┆ 2015-03   ┆ 0         ┆ 0         ┆ … ┆ 2         ┆ region_5 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 22        ┆ 9         │
│ 41530     ┆ 2015-04   ┆ 0         ┆ 0         ┆ … ┆ 2         ┆ region_5 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 22        ┆ 9         │
│ 41530     ┆ 2015-05   ┆ 2         ┆ 18        ┆ … ┆ 2         ┆ region_5 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 22        ┆ 9         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

## 4. monthly_territory_demand

In [28]:
territory_demand = pl.read_parquet(INTERMEDIATE + "/monthly_territory_demand.parquet")
print("Shape:", territory_demand.shape)
territory_demand.dtypes

Shape: (16191, 12)

[String,
 String,
 Int64,
 Float64,
 Int64,
 Float64,
 Int64,
 Float64,
 UInt32,
 String,
 String,
 String]

In [29]:
territory_demand.describe()

shape: (9, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ statistic ┆ territory ┆ year_mont ┆ net_quant ┆ … ┆ n_unique_ ┆ region   ┆ district  ┆ province  │
│ ---       ┆ _id       ┆ h         ┆ ity       ┆   ┆ skus      ┆ ---      ┆ ---       ┆ ---       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str      ┆ str       ┆ str       │
│           ┆ str       ┆ str       ┆ f64       ┆   ┆ f64       ┆          ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ count     ┆ 16191     ┆ 16191     ┆ 16191.0   ┆ … ┆ 16191.0   ┆ 16191    ┆ 16191     ┆ 16191     │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0        ┆ 0         ┆ 0         │
│ t         ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ mean      ┆ null      ┆ null      ┆ 17762.933 ┆ … ┆ 379.13643 ┆ null     ┆ null      ┆ null      │
│           ┆           ┆           ┆ 049       ┆   ┆ 4         ┆          ┆           ┆           │
│ std       ┆ null      ┆ null      ┆ 30787.145 ┆ … ┆ 281.81537 ┆ null     ┆ null      ┆ null      │
│           ┆           ┆           ┆ 604       ┆   ┆ 5         ┆          ┆           ┆           │
│ min       ┆ 10        ┆ 2015-01   ┆ -59151.0  ┆ … ┆ 0.0       ┆ region_1 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 1         ┆ 1         │
│ 25%       ┆ null      ┆ null      ┆ 4907.0    ┆ … ┆ 169.0     ┆ null     ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null      ┆ 11965.0   ┆ … ┆ 359.0     ┆ null     ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null      ┆ 21737.0   ┆ … ┆ 548.0     ┆ null     ┆ null      ┆ null      │
│ max       ┆ 99        ┆ 2020-03   ┆ 1.357226e ┆ … ┆ 1612.0    ┆ region_9 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆ 6         ┆   ┆           ┆          ┆ 9         ┆ 9         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [30]:
territory_demand.head()

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ territory ┆ year_mont ┆ net_quant ┆ net_sales ┆ … ┆ n_unique_ ┆ region   ┆ district  ┆ province  │
│ _id       ┆ h         ┆ ity       ┆ ---       ┆   ┆ skus      ┆ ---      ┆ ---       ┆ ---       │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ str      ┆ str       ┆ str       │
│ str       ┆ str       ┆ i64       ┆           ┆   ┆ u32       ┆          ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 218       ┆ 2015-01   ┆ 21153     ┆ 437532.24 ┆ … ┆ 314       ┆ region_6 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 6         ┆ 3         │
│ 218       ┆ 2015-02   ┆ 30445     ┆ 666925.5  ┆ … ┆ 415       ┆ region_6 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 6         ┆ 3         │
│ 218       ┆ 2015-03   ┆ 17249     ┆ 561422.32 ┆ … ┆ 520       ┆ region_6 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 6         ┆ 3         │
│ 218       ┆ 2015-04   ┆ 21653     ┆ 441844.15 ┆ … ┆ 350       ┆ region_6 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 6         ┆ 3         │
│ 218       ┆ 2015-05   ┆ 32454     ┆ 674005.55 ┆ … ┆ 523       ┆ region_6 ┆ district_ ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ 6         ┆ 3         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

## 5. outlet_features

In [31]:
outlet_features = pl.read_parquet(INTERMEDIATE + "/outlet_features.parquet")
print("Shape:", outlet_features.shape)
outlet_features.dtypes

Shape: (116183, 18)

[String,
 Float64,
 Int64,
 UInt32,
 Float64,
 Float64,
 Float64,
 Float64,
 UInt32,
 UInt32,
 Float64,
 Int64,
 Float64,
 Float64,
 Boolean,
 String,
 String,
 String]

In [32]:
outlet_features.describe()

shape: (9, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ statistic ┆ outlet_id ┆ total_net ┆ total_qua ┆ … ┆ is_active ┆ territory ┆ region   ┆ province  │
│ ---       ┆ ---       ┆ _sales    ┆ ntity     ┆   ┆ ---       ┆ _id       ┆ ---      ┆ ---       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ str      ┆ str       │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆ str       ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ count     ┆ 116183    ┆ 116183.0  ┆ 116183.0  ┆ … ┆ 116183.0  ┆ 116183    ┆ 116183   ┆ 116183    │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0         ┆ 0        ┆ 0         │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ mean      ┆ null      ┆ 31042.776 ┆ 686.75866 ┆ … ┆ 0.574404  ┆ null      ┆ null     ┆ null      │
│           ┆           ┆ 594       ┆ 5         ┆   ┆           ┆           ┆          ┆           │
│ std       ┆ null      ┆ 279334.83 ┆ 6637.5699 ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│           ┆           ┆ 5271      ┆           ┆   ┆           ┆           ┆          ┆           │
│ min       ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 10        ┆ region_1 ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 1         │
│ 25%       ┆ null      ┆ 0.0       ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 50%       ┆ null      ┆ 1282.56   ┆ 37.0      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 75%       ┆ null      ┆ 11280.72  ┆ 294.0     ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ max       ┆ s097255   ┆ 3.3886e7  ┆ 860710.0  ┆ … ┆ 1.0       ┆ 99        ┆ region_9 ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 9         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [33]:
outlet_features.head()

shape: (5, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ outlet_id ┆ total_net ┆ total_qua ┆ active_mo ┆ … ┆ is_active ┆ territory ┆ region   ┆ province  │
│ ---       ┆ _sales    ┆ ntity     ┆ nths      ┆   ┆ ---       ┆ _id       ┆ ---      ┆ ---       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ bool      ┆ ---       ┆ str      ┆ str       │
│           ┆ f64       ┆ i64       ┆ u32       ┆   ┆           ┆ str       ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 38768     ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ false     ┆ 162       ┆ region_3 ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 3         │
│ 049131    ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ false     ┆ 105       ┆ region_5 ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 9         │
│ 718357    ┆ 4346.15   ┆ 66        ┆ 1         ┆ … ┆ true      ┆ 113       ┆ region_3 ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 3         │
│ 085281    ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ false     ┆ 4         ┆ region_6 ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 8         │
│ 88950     ┆ 7432.85   ┆ 370       ┆ 2         ┆ … ┆ true      ┆ 44        ┆ region_1 ┆ province_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 1         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘